### PR TITLE
Add explicit types to literals in COARE ocean surface flux scheme

### LINKED ISSUE #3105: shr_flux_mod.F90: Missing explicit typing of constants (Causes build failure on Summit)
This issue can be reproduced by creating a new case (e.g. --compset FC5AV1C-H01B --res ne4_ne4) and building it with default IBM XL compiler on Summit.

Error messages:
```
"cime/src/share/util/shr_flux_mod.F90", line 2454.26: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
"cime/src/share/util/shr_flux_mod.F90", line 2481.27: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "max".
"cime/src/share/util/shr_flux_mod.F90", line 2532.16: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
"cime/src/share/util/shr_flux_mod.F90", line 2573.16: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
** shr_flux_mod   === End of Compilation 1 ===
1501-511  Compilation failed for file shr_flux_mod.F90.
gmake: *** [shr_flux_mod.o] Error 1
```
This build issue was introduced by PR #2972

@jayeshkrishna proposed a fix (adding _r8 to 4 real constants) which seems to work:
```
--- a/cime/src/share/util/shr_flux_mod.F90
+++ b/cime/src/share/util/shr_flux_mod.F90
@@ -2451,7 +2451,7 @@ jcool=0
      rr = zo*usr/visa
-     zoq= min(1.15e-4,5.5e-5/rr**.6)
+     zoq= min(1.15e-4_r8,5.5e-5/rr**.6)

    !****** transfer coeffs relative to ut @meas. hts ******
-   Cd= tau/rhoa/ut/max(.1,du)
+   Cd= tau/rhoa/ut/max(.1_r8,du)

@@ -2529,7 +2529,7 @@ real(R8) ::c,x,psik,psic,f
 ! Beljaars & Holtslag (1991)
-     c=min(50.,.35*zet)
+     c=min(50.0_r8,.35*zet)

@@ -2570,7 +2570,7 @@ real(R8) ::c,x,psik,psic,f
 ! Beljaars & Holtslag (1991)
-     c=min(50.,.35*zet)
+     c=min(50.0_r8,.35*zet)
```

### PR DESCRIPTION
**Pull request by JackReevesEyre**
The COARE ocean surface flux scheme had un-typed literals (including some in functions that caused a build issue on Summit). This change adds explicit types - in most cases converting to "_R8" reals. This shouldn't affect the climate of "out of the box" cases (which use a different ocean surface flux scheme). But, when using the COARE scheme (ocn_surface_flux_scheme = 1 in user_nl_cpl), it is non-BFB with the earlier COARE implementation. 

Fixes #3105

[BFB] [FCC]

### CODE REVIEW

**Comment by JackReevesEyre** [comment]
Design document:
https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1007223202/W14+Alternative+ocean+surface+flux+schemes+Design+Document?focusedCommentId=1020461112#comment-1020461112

**Comment by JackReevesEyre** [comment]
This commit has been tested on Summit (@dqwu) and fixed the IBM XL compiler build failures. 

It has been tested on Anvil with the COARE scheme active (i.e., ocn_surface_flux_scheme = 1 in user_nl_cpl): it built and ran successfully but gave different answers to the pre-bug fix version (due to changed types/kinds of some constants).

**Comment by dqwu** [comment]
@kaizhangpnl @singhbalwinder 
I think this PR is ready to be merged to next and master.

**Comment by kaizhangpnl** [comment]
Sorry, I missed the notification (to review the commit). Just approved it.

**Comment by singhbalwinder** [comment]
Thanks! I will merge it today.

**Comment by singhbalwinder** [comment]
Pushed to next
