### ISSUE TITLE
ALM fails to compile with PGI 13.9 on Blues

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#470]
Similar to #457.

The new ALM feature development (BeTR) fails to compile and causing following tests to fail:
- SMS.hcru_hcru.I1850CRUCLM45CN
- SMS.f19_f19.I1850CLM45CN 
- SMS.f09_g16_a.IGCLM45_MLI
- SMS.f09_g16.I1850CLM45CN

All above cases successfully compile with PGI 15.3.0 on Titan.

The compilation error on Blues is:

```
mpif90  -c -I.  -I/lcrc/project/ACME/gbisht/acme_scratch/sharedlibroot.20151112_234606/pgi/mpich/nodebug/nothreads/include -I/lcrc/project/ACME/gbisht/acme_scratch/sharedlibroot.20151112_234606/pgi/mpich/nodebug/nothreads/MCT/noesmf/a1l1r1i1o1g1w1/csm_share -I/home/jacob/netcdf-4.3.3.1pg13.9/include -I/soft/mpich2/1.4.1-pgi-13.9//include -I/soft/pnetcdf/1.5.0/pgi-13.9/mpich2-1.4.1/include -I/lcrc/project/ACME/gbisht/acme_scratch/sharedlibroot.20151112_234606/pgi/mpich/nodebug/nothreads/include -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/cime/share/csm_share/shr -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/cime/share/csm_share/include -I. -I/lcrc/project/ACME/gbisht/acme_scratch/SMS.hcru_hcru.I1850CRUCLM45CN.blues_pgi.G.20151112_234606/SourceMods/src.clm -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/main -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/betr_math -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/betr_core -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_sminn -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/biogeophys -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/biogeochem -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/dyn_subgrid -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/ED -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/ED/main -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/ED/biogeophys -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/ED/biogeochem -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/ED/fire -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/utils -I/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/cpl -I/lcrc/project/ACME/gbisht/acme_scratch/SMS.hcru_hcru.I1850CRUCLM45CN.blues_pgi.G.20151112_234606/bld/lib/include  -i4 -gopt  -time -Mextend -byteswapio -Mflushz -Kieee     -DLINUX  -DNDEBUG -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_SHR_VMATH -DNO_R16   -DLINUX -DCPRPGI  -DHAVE_SLASHPROC -Mfree  -DUSE_CONTIGUOUS= /blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90
PGF90-S-0038-Symbol, initallocate, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, init, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, initallocate, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, init, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, initallocate, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, init, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, initallocate, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
PGF90-S-0038-Symbol, init, has not been explicitly declared (/blues/gpfs/home/gbisht/Projects/ACME/repos/ACME/components/clm/src/betr/bgc_century/BGCReactionsCenturyCLM3Type.F90)
  0 inform,   0 warnings,   8 severes, 0 fatal for constructor
gmake: *** [BGCReactionsCenturyCLM3Type.o] Error 2
ERROR: clm.buildlib gmake complib -j 1 MODEL=clm COMPLIB=/lcrc/project/ACME/gbisht/acme_scratch/sharedlibroot.20151112_234606/pgi/mpich/nodebug/nothreads/MCT/noesmf//lib/libclm.a USER_CPPDEFS=" " -f /lcrc/project/ACME/gbisht/acme_scratch/SMS.hcru_hcru.I1850CRUCLM45CN.blues_pgi.G.20151112_234606/Tools/Makefile failed: 512
```

@jinyuntang: FYI.
