### ISSUE TITLE
ALM fails to compile with Intel 13.1 on Blues

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#471]
Compile time errors in BGCCenturySubMod.F90.   One line is below and full output is at https://gist.github.com/rljacob/bb69683794ebcce09921

/lcrc/group/earthscience/jacob/ACMEpure/components/clm/src/betr/bgc_century/BGCCenturySubMod.F90(151): error #6780: A dummy argument with the INTENT(IN) attribute shall not be defined nor become undefined.   [PRIMVARID]
    primvarid(reac)       = (lit1-1)*nelms+c_loc
----^
