### ISSUE TITLE
shr_flux_mod.F90: Missing explicit typing of constants (Causes build failure on Summit)

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3105]
This issue can be reproduced by creating a new case (e.g. --compset FC5AV1C-H01B --res ne4_ne4) and building it with default IBM XL compiler on Summit.

Error messages:
```
"cime/src/share/util/shr_flux_mod.F90", line 2454.26: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
"cime/src/share/util/shr_flux_mod.F90", line 2481.27: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "max".
"cime/src/share/util/shr_flux_mod.F90", line 2532.16: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
"cime/src/share/util/shr_flux_mod.F90", line 2573.16: 1513-041 (S) Arguments of the wrong type were specified for the INTRINSIC procedure "min".
** shr_flux_mod   === End of Compilation 1 ===
1501-511  Compilation failed for file shr_flux_mod.F90.
gmake: *** [shr_flux_mod.o] Error 1
```
This build issue was introduced by PR #2972

@jayeshkrishna proposed a fix (adding _r8 to 4 real constants) which seems to work:
```
--- a/cime/src/share/util/shr_flux_mod.F90
+++ b/cime/src/share/util/shr_flux_mod.F90
@@ -2451,7 +2451,7 @@ jcool=0
      rr = zo*usr/visa
-     zoq= min(1.15e-4,5.5e-5/rr**.6)
+     zoq= min(1.15e-4_r8,5.5e-5/rr**.6)

    !****** transfer coeffs relative to ut @meas. hts ******
-   Cd= tau/rhoa/ut/max(.1,du)
+   Cd= tau/rhoa/ut/max(.1_r8,du)

@@ -2529,7 +2529,7 @@ real(R8) ::c,x,psik,psic,f
 ! Beljaars & Holtslag (1991)
-     c=min(50.,.35*zet)
+     c=min(50.0_r8,.35*zet)

@@ -2570,7 +2570,7 @@ real(R8) ::c,x,psik,psic,f
 ! Beljaars & Holtslag (1991)
-     c=min(50.,.35*zet)
+     c=min(50.0_r8,.35*zet)
```

**Comment by sarats** [comment]
I wonder if there is a Fortran lint tool that catches this kind of error as we repeatedly run into them.

**Comment by sarats** [comment]
Found a Intel compiler forum request on a related topic:
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/269439

**Comment by sarats** [comment]
For GNU, perhaps we ought to see if following options make sense ...
https://gcc.gnu.org/onlinedocs/gfortran/Error-and-Warning-Options.html
```
-Wconversion
    Warn about implicit conversions that are likely to change the value of the expression after conversion. Implied by -Wall.

-Wconversion-extra
    Warn about implicit conversions between different types and kinds. This option does not imply -Wconversion.
```

**Comment by JackReevesEyre** [comment]
I have created a branch for this bug fix and made the changes suggested by @jayeshkrishna. However, the subroutines containing those issues are full of many other literal real types without a kind suffix (i.e., no "_R8"). Is it best to change all of them or is it not a big deal?

**Comment by rljacob** [comment]
go ahead and change all of them.  All literals must be explicitly typed.  We're trying to locate a script we once had to help with that.

**Comment by JackReevesEyre** [comment]
I have changed all of these manually, and am in the process of testing (it builds OK on Anvil, and the job is in the queue). I don't have Summit access, so if someone that does can test it there I would appreciate it. The branch is: 
https://github.com/E3SM-Project/E3SM/tree/jackreeveseyre/cime/sfc_flux_bug_fix

The code that contained the problem is not enabled by default, so it should be BFB in standard developer tests. I will test separately to see if the changes affect answers with this subroutine enabled.

**Comment by JackReevesEyre** [comment]
@kaizhangpnl - I thought you might want to know about this issue. I changed the COARE code to deal with this bug and related issues (types and kinds of literals in the COARE subroutines). The new version is not BFB with the previous commit (in two tests with COARE enabled: ocn_surface_flux_scheme = 1). Should I make further changes to try and get it BFB with earlier COARE version?

**Comment by rljacob** [comment]
@dqwu or @sarats can one of you try out the branch above?

It doesn't need to be BFB.

**Comment by kaizhangpnl** [comment]
@JackReevesEyre I just had a look at the code changes. The shift from floating numbers to double precision numbers indeed will cause non-bit-for-bit changes.

**Comment by sarats** [comment]
@dqwu Please try  https://github.com/E3SM-Project/E3SM/tree/jackreeveseyre/cime/sfc_flux_bug_fix and see if it resolves your issues.

**Comment by dqwu** [comment]
@sarats 
That branch looks good to me, no more XL compiler build errors.

I rebased it to a commit before PR 3092 was merged (but picked the fix for MPI module in PR 3115), as a workaround for the confirmed job script submission error. The following two low-res cases passed:
--compset FC5AV1C-H01B --res ne4_ne4
--compset CMPASO-NYF --res T62_oQU120

**Comment by dqwu** [comment]
@JackReevesEyre 
PR 3132 has fixed batch submission command for Summit.
I rebased jackreeveseyre/cime/sfc_flux_bug_fix branch
to latest master and it looks good to run ne4_ne4 F case.
